// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug: Log the Supabase URL being used (check browser console)
if (typeof window !== 'undefined') {
  console.log('🔍 Supabase URL:', SUPABASE_URL);
  console.log('🔍 Supabase Key exists:', !!SUPABASE_PUBLISHABLE_KEY);
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error('❌ Missing Supabase environment variables!');
    console.error('Expected: VITE_SUPABASE_URL=https://fjkwpxppsblagioijjbs.supabase.co (Lovable project)');
    console.error('OR: VITE_SUPABASE_URL=https://zsvwohwgvjshtmeoulte.supabase.co (Your project)');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});